#! /bin/bash
echo "Build and run a container from the docker composition identified by $1=name (e.g. apache)."
echo "Build and run all containers if name is not specified."
echo "   NOTE: name is defined in docker-compose.yml at top level (e.g. apache:)"
echo " "
CMD="docker-compose up -d $1"
echo "$CMD"
$CMD

