#! /bin/bash
echo '=============================================================='
echo '  All Containers - List all docker containers running or not'
echo '=============================================================='
CMD="docker container ls -a"
echo "$CMD"
$CMD

