#! /bin/bash
echo "Stop running and remove a container from the docker composition identified by $1=name (e.g. apache)."
echo "Stop and remove all containers defined in docker composition if name is not specified."
echo "   NOTE: name is defined in docker-compose.yml at top level (e.g. apache:)"
echo " "
CMD="docker-compose down $1"
echo "$CMD"
$CMD

# list all running images, containers, services, and volumes
dls

