#! /bin/bash
echo '=============================================================='
echo '  Running Containers - List only running docker containers '
echo '=============================================================='
CMD="docker container ls"
echo "$CMD"
$CMD

