#! /bin/bash
echo 'Stop all running containers'
echo ' '
echo 'docker container stop $(docker ps -a -q)'
docker container stop $(docker ps -a -q)

# list all running images, containers, services, and volumes
dls
