#! /bin/bash
echo 'Stop a container by docker assigned name (e.g. $1=sleepy_boyd) or id (e.g. $1=fb213)'
echo " "
CMD="docker container stop $1"
echo "$CMD"
$CMD

# list all running images, containers, services, and volumes
dls
