#! /bin/bash
echo '=============================================================='
echo '  Images - List docker images '
echo '=============================================================='
CMD="docker image ls"
echo "$CMD"
$CMD


