#! /bin/bash
echo 'List all docker images, containers, services, and volumes'
echo ' '
# ----------------------
#         images
# ----------------------
dils
echo ' '
# ----------------------
#   running containers
# ----------------------
dcrun
echo ' '
# ----------------------
#     all containers
# ----------------------
dcall
echo ' '
# ----------------------
#        services
# ----------------------
dcpls
echo ' '

# ----------------------
#        volumes
# ----------------------
dvls
echo ' '
