#! /bin/bash
echo '=============================================================='
echo '  Volumes - List all docker volumes'
echo '=============================================================='
CMD="docker volume ls"
echo "$CMD"
$CMD

